"""initial schema

Revision ID: 0007_fabrication_batches
Revises:
Create Date: 2026-08-06 21:16:19.293513
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0007_fabrication_batches'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_layout_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('substrate_width_mm', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('substrate_length_mm', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('devices_per_substrate', sa.Integer(), nullable=False),
    sa.Column('device_active_area_cm2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_active_area_cm2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('device_active_area_cm2 > 0', name=op.f('ck_device_layout_versions_positive_active_area')),
    sa.CheckConstraint('devices_per_substrate > 0', name=op.f('ck_device_layout_versions_positive_devices_per_substrate')),
    sa.CheckConstraint('substrate_length_mm > 0', name=op.f('ck_device_layout_versions_positive_substrate_length')),
    sa.CheckConstraint('substrate_width_mm > 0', name=op.f('ck_device_layout_versions_positive_substrate_width')),
    sa.CheckConstraint('version > 0', name=op.f('ck_device_layout_versions_positive_layout_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_layout_versions')),
    sa.UniqueConstraint('code', 'version', name='uq_device_layouts_code_version')
    )
    op.create_index('ix_device_layout_versions_code', 'device_layout_versions', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('student', 'instructor', 'administrator')", name=op.f('ck_users_valid_role')),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_nonnegative_login_failures')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_actor_user_id', 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_table('baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('device_recipe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('deposition_process', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived')", name=op.f('ck_baselines_valid_baseline_status')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_baselines_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_version_id'], ['baseline_versions.id'], name='fk_baselines_current_version_id_baseline_versions', ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_baselines_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baselines')),
    sa.UniqueConstraint('name', name=op.f('uq_baselines_name'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'closed', 'archived')", name=op.f('ck_campaigns_valid_campaign_status')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_campaigns_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('code', name=op.f('uq_campaigns_code'))
    )
    op.create_index('ix_campaigns_status_id', 'campaigns', ['status', 'id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.String(length=160), nullable=True),
    sa.Column('experiment_code', sa.String(length=200), nullable=False),
    sa.Column('series_version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('plan_type', sa.String(length=24), nullable=True),
    sa.Column('plan_status', sa.String(length=24), nullable=True),
    sa.CheckConstraint("plan_status IS NULL OR plan_status IN ('draft', 'pending_approval', 'approved', 'released', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_experiments_valid_plan_status')),
    sa.CheckConstraint("plan_type IS NULL OR plan_type IN ('comparative', 'standalone')", name=op.f('ck_experiments_valid_plan_type')),
    sa.CheckConstraint("status IN ('suggested', 'running', 'completed', 'failed')", name=op.f('ck_experiments_valid_status')),
    sa.CheckConstraint('series_version > 0', name=op.f('ck_experiments_positive_series_version')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.code'], name=op.f('fk_experiments_campaign_id_campaigns'), ondelete='RESTRICT', use_alter=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_experiments_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('campaign_id', 'series_version', name='uq_experiments_campaign_series_version'),
    sa.UniqueConstraint('experiment_code', name=op.f('uq_experiments_experiment_code'))
    )
    op.create_index('ix_experiments_campaign_id_id', 'experiments', ['campaign_id', 'id'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_sessions'))
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('baseline_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('recipe_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('recipe_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision_number > 0', name=op.f('ck_baseline_versions_positive_revision_number')),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], name=op.f('fk_baseline_versions_baseline_id_baselines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_baseline_versions_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseline_versions')),
    sa.UniqueConstraint('baseline_id', 'revision_number', name='uq_baseline_versions_baseline_revision')
    )
    op.create_index('ix_baseline_versions_baseline_id', 'baseline_versions', ['baseline_id'], unique=False)
    op.create_table('fabrication_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('condition_set_hash', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'ready', 'in_progress', 'completed', 'cancelled')", name=op.f('ck_fabrication_batches_valid_batch_status')),
    sa.CheckConstraint('batch_number > 0', name=op.f('ck_fabrication_batches_positive_batch_number')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_fabrication_batches_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_fabrication_batches_experiment_id_experiments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabrication_batches')),
    sa.UniqueConstraint('batch_code', name=op.f('uq_fabrication_batches_batch_code')),
    sa.UniqueConstraint('experiment_id', 'batch_number', name='uq_batches_experiment_number')
    )
    op.create_index('ix_fabrication_batches_experiment_id', 'fabrication_batches', ['experiment_id'], unique=False)
    op.create_index('ix_fabrication_batches_status', 'fabrication_batches', ['status'], unique=False)
    op.create_table('result_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('fabrication_batch_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('group_assignment', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('analysis_schema_version', sa.Integer(), server_default='2', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_result_files_positive_size')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_result_files_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_result_files_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fabrication_batch_id'], ['fabrication_batches.id'], name=op.f('fk_result_files_fabrication_batch_id_fabrication_batches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_files'))
    )
    op.create_index('ix_result_files_batch_id', 'result_files', ['fabrication_batch_id'], unique=False)
    op.create_index('ix_result_files_experiment_id', 'result_files', ['experiment_id'], unique=False)
    op.create_table('experiment_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('condition_code', sa.String(length=208), nullable=False),
    sa.Column('condition_name', sa.String(length=120), nullable=False),
    sa.Column('recipe_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recipe_schema_version', sa.Integer(), server_default='3', nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('source_baseline_version_id', sa.Integer(), nullable=True),
    sa.Column('device_layout_code', sa.String(length=40), nullable=False),
    sa.Column('device_layout_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('planned_substrate_count', sa.Integer(), nullable=False),
    sa.Column('expected_device_count', sa.Integer(), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("role IN ('control', 'target', 'standalone')", name=op.f('ck_experiment_conditions_valid_condition_role')),
    sa.CheckConstraint('expected_device_count >= 1', name=op.f('ck_experiment_conditions_positive_expected_device_count')),
    sa.CheckConstraint('planned_substrate_count >= 1', name=op.f('ck_experiment_conditions_positive_substrate_count')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_experiment_conditions_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_conditions_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_baseline_version_id'], ['baseline_versions.id'], name='fk_experiment_conditions_source_baseline_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_conditions')),
    sa.UniqueConstraint('experiment_id', 'condition_code', name='uq_conditions_experiment_code')
    )
    op.create_index('ix_experiment_conditions_experiment_id', 'experiment_conditions', ['experiment_id'], unique=False)
    op.create_table('process_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabrication_batch_id', sa.Integer(), nullable=False),
    sa.Column('execution_code', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('layer_role', sa.String(length=80), nullable=False),
    sa.Column('layer_type', sa.String(length=80), nullable=False),
    sa.Column('layer_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='planned', nullable=False),
    sa.Column('is_shared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('planned_process_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('planned_snapshot_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('planned_canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('actual_process_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actual_snapshot_schema_version', sa.Integer(), nullable=True),
    sa.Column('actual_canonical_hash', sa.String(length=64), nullable=True),
    sa.Column('actual_recording_mode', sa.String(length=24), nullable=True),
    sa.Column('equipment_identifier', sa.String(length=120), nullable=True),
    sa.Column('executed_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('spin_coating', 'annealing', 'vcd', 'thermal_evaporation', 'ald', 'sputtering')", name=op.f('ck_process_executions_valid_execution_method')),
    sa.CheckConstraint("actual_recording_mode IS NULL OR actual_recording_mode IN ('copied_from_plan', 'entered')", name=op.f('ck_process_executions_valid_process_actual_recording_mode')),
    sa.CheckConstraint('(actual_process_snapshot IS NULL AND actual_snapshot_schema_version IS NULL AND actual_canonical_hash IS NULL AND actual_recording_mode IS NULL) OR (actual_process_snapshot IS NOT NULL AND actual_snapshot_schema_version IS NOT NULL AND actual_canonical_hash IS NOT NULL AND actual_recording_mode IS NOT NULL)', name=op.f('ck_process_executions_complete_process_actual_metadata')),
    sa.CheckConstraint("status IN ('planned', 'ready', 'running', 'completed', 'failed', 'cancelled')", name=op.f('ck_process_executions_valid_execution_status')),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], name=op.f('fk_process_executions_executed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabrication_batch_id'], ['fabrication_batches.id'], name=op.f('fk_process_executions_fabrication_batch_id_fabrication_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_executions')),
    sa.UniqueConstraint('execution_code', name=op.f('uq_process_executions_execution_code'))
    )
    op.create_index('ix_process_executions_batch_id', 'process_executions', ['fabrication_batch_id'], unique=False)
    op.create_table('solution_preparations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabrication_batch_id', sa.Integer(), nullable=False),
    sa.Column('preparation_code', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='planned', nullable=False),
    sa.Column('planned_solution_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('planned_snapshot_schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('planned_canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('actual_solution_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actual_snapshot_schema_version', sa.Integer(), nullable=True),
    sa.Column('actual_canonical_hash', sa.String(length=64), nullable=True),
    sa.Column('actual_recording_mode', sa.String(length=24), nullable=True),
    sa.Column('prepared_by_id', sa.Integer(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'preparing', 'ready', 'consumed', 'discarded')", name=op.f('ck_solution_preparations_valid_preparation_status')),
    sa.CheckConstraint("actual_recording_mode IS NULL OR actual_recording_mode IN ('copied_from_plan', 'entered')", name=op.f('ck_solution_preparations_valid_solution_actual_recording_mode')),
    sa.CheckConstraint('(actual_solution_snapshot IS NULL AND actual_snapshot_schema_version IS NULL AND actual_canonical_hash IS NULL AND actual_recording_mode IS NULL) OR (actual_solution_snapshot IS NOT NULL AND actual_snapshot_schema_version IS NOT NULL AND actual_canonical_hash IS NOT NULL AND actual_recording_mode IS NOT NULL)', name=op.f('ck_solution_preparations_complete_solution_actual_metadata')),
    sa.ForeignKeyConstraint(['fabrication_batch_id'], ['fabrication_batches.id'], name=op.f('fk_solution_preparations_fabrication_batch_id_fabrication_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by_id'], ['users.id'], name=op.f('fk_solution_preparations_prepared_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_preparations')),
    sa.UniqueConstraint('preparation_code', name=op.f('uq_solution_preparations_preparation_code'))
    )
    op.create_index('ix_solution_preparations_batch_id', 'solution_preparations', ['fabrication_batch_id'], unique=False)
    op.create_table('condition_substrate_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_id', sa.Integer(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('approved_condition_hash', sa.String(length=64), nullable=True),
    sa.CheckConstraint("decision IN ('pending', 'approved', 'rejected', 'invalidated')", name=op.f('ck_condition_substrate_exceptions_valid_exception_decision')),
    sa.CheckConstraint('requested_count >= 1', name=op.f('ck_condition_substrate_exceptions_positive_requested_count')),
    sa.ForeignKeyConstraint(['condition_id'], ['experiment_conditions.id'], name=op.f('fk_condition_substrate_exceptions_condition_id_experiment_conditions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_condition_substrate_exceptions_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_condition_substrate_exceptions_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_condition_substrate_exceptions'))
    )
    op.create_index('ix_condition_substrate_exceptions_condition_id', 'condition_substrate_exceptions', ['condition_id'], unique=False)
    op.create_index('uq_condition_active_substrate_exception', 'condition_substrate_exceptions', ['condition_id'], unique=True, sqlite_where=sa.text("decision IN ('pending', 'approved')"), postgresql_where=sa.text("decision IN ('pending', 'approved')"))
    op.create_table('fabrication_batch_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabrication_batch_id', sa.Integer(), nullable=False),
    sa.Column('source_condition_id', sa.Integer(), nullable=False),
    sa.Column('condition_code', sa.String(length=200), nullable=False),
    sa.Column('condition_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('source_condition_hash', sa.String(length=64), nullable=False),
    sa.Column('recipe_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('recipe_schema_version', sa.Integer(), nullable=False),
    sa.Column('device_layout_code', sa.String(length=40), nullable=False),
    sa.Column('device_layout_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('planned_substrate_count', sa.Integer(), nullable=False),
    sa.Column('expected_device_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('control', 'target', 'standalone')", name=op.f('ck_fabrication_batch_conditions_valid_batch_condition_role')),
    sa.CheckConstraint('expected_device_count >= 1', name=op.f('ck_fabrication_batch_conditions_positive_batch_device_count')),
    sa.CheckConstraint('planned_substrate_count >= 1', name=op.f('ck_fabrication_batch_conditions_positive_batch_substrate_count')),
    sa.ForeignKeyConstraint(['fabrication_batch_id'], ['fabrication_batches.id'], name=op.f('fk_fabrication_batch_conditions_fabrication_batch_id_fabrication_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_condition_id'], ['experiment_conditions.id'], name=op.f('fk_fabrication_batch_conditions_source_condition_id_experiment_conditions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabrication_batch_conditions')),
    sa.UniqueConstraint('fabrication_batch_id', 'condition_code', name='uq_batch_conditions_code')
    )
    op.create_index('ix_fabrication_batch_conditions_batch_id', 'fabrication_batch_conditions', ['fabrication_batch_id'], unique=False)
    op.create_index('ix_fabrication_batch_conditions_source_condition_id', 'fabrication_batch_conditions', ['source_condition_id'], unique=False)
    op.create_table('fabrication_substrates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_condition_id', sa.Integer(), nullable=False),
    sa.Column('substrate_ordinal', sa.Integer(), nullable=False),
    sa.Column('substrate_code', sa.String(length=200), nullable=False),
    sa.Column('substrate_mark', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='planned', nullable=False),
    sa.Column('notes', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed', 'failed', 'excluded')", name=op.f('ck_fabrication_substrates_valid_substrate_status')),
    sa.CheckConstraint('substrate_ordinal > 0', name=op.f('ck_fabrication_substrates_positive_substrate_ordinal')),
    sa.CheckConstraint('length(substrate_mark) = 3', name=op.f('ck_fabrication_substrates_valid_substrate_mark_length')),
    sa.ForeignKeyConstraint(['batch_condition_id'], ['fabrication_batch_conditions.id'], name=op.f('fk_fabrication_substrates_batch_condition_id_fabrication_batch_conditions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabrication_substrates')),
    sa.UniqueConstraint('batch_condition_id', 'substrate_ordinal', name='uq_substrates_condition_ordinal'),
    sa.UniqueConstraint('substrate_code', name=op.f('uq_fabrication_substrates_substrate_code'))
    )
    op.create_index('ix_fabrication_substrates_batch_condition_id', 'fabrication_substrates', ['batch_condition_id'], unique=False)
    op.create_table('solution_preparation_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_preparation_id', sa.Integer(), nullable=False),
    sa.Column('batch_condition_id', sa.Integer(), nullable=False),
    sa.Column('layer_ordinal', sa.Integer(), nullable=False),
    sa.Column('layer_role', sa.String(length=80), nullable=False),
    sa.Column('layer_type', sa.String(length=80), nullable=False),
    sa.Column('layer_snapshot_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['batch_condition_id'], ['fabrication_batch_conditions.id'], name=op.f('fk_solution_preparation_uses_batch_condition_id_fabrication_batch_conditions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['solution_preparation_id'], ['solution_preparations.id'], name=op.f('fk_solution_preparation_uses_solution_preparation_id_solution_preparations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_preparation_uses')),
    sa.UniqueConstraint('solution_preparation_id', 'batch_condition_id', 'layer_ordinal', name='uq_preparation_use_unique')
    )
    op.create_index('ix_preparation_uses_batch_condition_id', 'solution_preparation_uses', ['batch_condition_id'], unique=False)
    op.create_index('ix_preparation_uses_preparation_id', 'solution_preparation_uses', ['solution_preparation_id'], unique=False)
    op.create_table('fabrication_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('substrate_id', sa.Integer(), nullable=False),
    sa.Column('device_ordinal', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=200), nullable=False),
    sa.Column('device_mark', sa.String(length=4), nullable=False),
    sa.Column('device_active_area_cm2', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='planned', nullable=False),
    sa.Column('notes', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'active', 'completed', 'failed', 'excluded')", name=op.f('ck_fabrication_devices_valid_device_status')),
    sa.CheckConstraint('device_active_area_cm2 > 0', name=op.f('ck_fabrication_devices_positive_device_area')),
    sa.CheckConstraint('device_ordinal > 0', name=op.f('ck_fabrication_devices_positive_device_ordinal')),
    sa.CheckConstraint('length(device_mark) = 4', name=op.f('ck_fabrication_devices_valid_device_mark_length')),
    sa.ForeignKeyConstraint(['substrate_id'], ['fabrication_substrates.id'], name=op.f('fk_fabrication_devices_substrate_id_fabrication_substrates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fabrication_devices')),
    sa.UniqueConstraint('device_code', name=op.f('uq_fabrication_devices_device_code')),
    sa.UniqueConstraint('substrate_id', 'device_ordinal', name='uq_devices_substrate_ordinal')
    )
    op.create_index('ix_fabrication_devices_substrate_id', 'fabrication_devices', ['substrate_id'], unique=False)
    op.create_table('result_device_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_file_id', sa.Integer(), nullable=False),
    sa.Column('analysis_device_id', sa.String(length=80), nullable=False),
    sa.Column('analysis_substrate_id', sa.Text(), nullable=False),
    sa.Column('instrument_label', sa.Text(), nullable=False),
    sa.Column('batch_condition_id', sa.Integer(), nullable=False),
    sa.Column('fabrication_device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_condition_id'], ['fabrication_batch_conditions.id'], name=op.f('fk_result_device_assignments_batch_condition_id_fabrication_batch_conditions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fabrication_device_id'], ['fabrication_devices.id'], name=op.f('fk_result_device_assignments_fabrication_device_id_fabrication_devices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_file_id'], ['result_files.id'], name=op.f('fk_result_device_assignments_result_file_id_result_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_device_assignments')),
    sa.UniqueConstraint('result_file_id', 'analysis_device_id', name='uq_result_assignment_analysis_device'),
    sa.UniqueConstraint('result_file_id', 'fabrication_device_id', name='uq_result_assignment_fabrication_device')
    )
    op.create_index('ix_result_device_assignments_fabrication_device_id', 'result_device_assignments', ['fabrication_device_id'], unique=False)
    op.create_index('ix_result_device_assignments_batch_condition_id', 'result_device_assignments', ['batch_condition_id'], unique=False)
    op.create_index('ix_result_device_assignments_result_file_id', 'result_device_assignments', ['result_file_id'], unique=False)
    op.create_table('process_execution_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_execution_id', sa.Integer(), nullable=False),
    sa.Column('substrate_id', sa.Integer(), nullable=False),
    sa.Column('batch_condition_id', sa.Integer(), nullable=False),
    sa.Column('layer_ordinal', sa.Integer(), nullable=False),
    sa.Column('layer_snapshot_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['batch_condition_id'], ['fabrication_batch_conditions.id'], name=op.f('fk_process_execution_members_batch_condition_id_fabrication_batch_conditions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_execution_id'], ['process_executions.id'], name=op.f('fk_process_execution_members_process_execution_id_process_executions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substrate_id'], ['fabrication_substrates.id'], name=op.f('fk_process_execution_members_substrate_id_fabrication_substrates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_execution_members')),
    sa.UniqueConstraint('process_execution_id', 'substrate_id', 'layer_ordinal', name='uq_execution_member_unique')
    )
    op.create_index('ix_execution_members_execution_id', 'process_execution_members', ['process_execution_id'], unique=False)
    op.create_index('ix_execution_members_substrate_id', 'process_execution_members', ['substrate_id'], unique=False)
    op.create_table('execution_deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fabrication_batch_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planned_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actual_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes_deviation_id', sa.Integer(), nullable=True),
    sa.Column('solution_preparation_id', sa.Integer(), nullable=True),
    sa.Column('process_execution_id', sa.Integer(), nullable=True),
    sa.Column('substrate_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('process', 'material', 'equipment', 'substrate', 'device', 'operator', 'other')", name=op.f('ck_execution_deviations_valid_deviation_category')),
    sa.CheckConstraint("severity IN ('info', 'warning', 'error', 'critical')", name=op.f('ck_execution_deviations_valid_deviation_severity')),
    sa.CheckConstraint('(CASE WHEN solution_preparation_id IS NULL THEN 0 ELSE 1 END + CASE WHEN process_execution_id IS NULL THEN 0 ELSE 1 END + CASE WHEN substrate_id IS NULL THEN 0 ELSE 1 END + CASE WHEN device_id IS NULL THEN 0 ELSE 1 END) <= 1', name=op.f('ck_execution_deviations_at_most_one_deviation_target')),
    sa.ForeignKeyConstraint(['device_id'], ['fabrication_devices.id'], name=op.f('fk_execution_deviations_device_id_fabrication_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fabrication_batch_id'], ['fabrication_batches.id'], name=op.f('fk_execution_deviations_fabrication_batch_id_fabrication_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['process_execution_id'], ['process_executions.id'], name=op.f('fk_execution_deviations_process_execution_id_process_executions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_execution_deviations_recorded_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solution_preparation_id'], ['solution_preparations.id'], name=op.f('fk_execution_deviations_solution_preparation_id_solution_preparations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['substrate_id'], ['fabrication_substrates.id'], name=op.f('fk_execution_deviations_substrate_id_fabrication_substrates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_deviation_id'], ['execution_deviations.id'], name=op.f('fk_execution_deviations_supersedes_deviation_id_execution_deviations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_deviations'))
    )
    op.create_index('ix_execution_deviations_batch_id', 'execution_deviations', ['fabrication_batch_id'], unique=False)
    op.create_index('ix_execution_deviations_supersedes', 'execution_deviations', ['supersedes_deviation_id'], unique=False)
    op.create_foreign_key(
        'fk_baselines_current_version_id_baseline_versions',
        'baselines',
        'baseline_versions',
        ['current_version_id'],
        ['id'],
        ondelete='RESTRICT',
    )
    op.create_foreign_key(
        'fk_experiments_campaign_id_campaigns',
        'experiments',
        'campaigns',
        ['campaign_id'],
        ['code'],
        ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_experiments_campaign_id_campaigns',
        'experiments',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_baselines_current_version_id_baseline_versions',
        'baselines',
        type_='foreignkey',
    )
    op.drop_index('ix_execution_deviations_supersedes', table_name='execution_deviations')
    op.drop_index('ix_execution_deviations_batch_id', table_name='execution_deviations')
    op.drop_table('execution_deviations')
    op.drop_index('ix_execution_members_substrate_id', table_name='process_execution_members')
    op.drop_index('ix_execution_members_execution_id', table_name='process_execution_members')
    op.drop_table('process_execution_members')
    op.drop_index('ix_result_device_assignments_result_file_id', table_name='result_device_assignments')
    op.drop_index('ix_result_device_assignments_batch_condition_id', table_name='result_device_assignments')
    op.drop_index('ix_result_device_assignments_fabrication_device_id', table_name='result_device_assignments')
    op.drop_table('result_device_assignments')
    op.drop_index('ix_fabrication_devices_substrate_id', table_name='fabrication_devices')
    op.drop_table('fabrication_devices')
    op.drop_index('ix_preparation_uses_preparation_id', table_name='solution_preparation_uses')
    op.drop_index('ix_preparation_uses_batch_condition_id', table_name='solution_preparation_uses')
    op.drop_table('solution_preparation_uses')
    op.drop_index('ix_fabrication_substrates_batch_condition_id', table_name='fabrication_substrates')
    op.drop_table('fabrication_substrates')
    op.drop_index('ix_fabrication_batch_conditions_source_condition_id', table_name='fabrication_batch_conditions')
    op.drop_index('ix_fabrication_batch_conditions_batch_id', table_name='fabrication_batch_conditions')
    op.drop_table('fabrication_batch_conditions')
    op.drop_index('uq_condition_active_substrate_exception', table_name='condition_substrate_exceptions', sqlite_where=sa.text("decision IN ('pending', 'approved')"), postgresql_where=sa.text("decision IN ('pending', 'approved')"))
    op.drop_index('ix_condition_substrate_exceptions_condition_id', table_name='condition_substrate_exceptions')
    op.drop_table('condition_substrate_exceptions')
    op.drop_index('ix_solution_preparations_batch_id', table_name='solution_preparations')
    op.drop_table('solution_preparations')
    op.drop_index('ix_process_executions_batch_id', table_name='process_executions')
    op.drop_table('process_executions')
    op.drop_index('ix_experiment_conditions_experiment_id', table_name='experiment_conditions')
    op.drop_table('experiment_conditions')
    op.drop_index('ix_result_files_experiment_id', table_name='result_files')
    op.drop_index('ix_result_files_batch_id', table_name='result_files')
    op.drop_table('result_files')
    op.drop_index('ix_fabrication_batches_status', table_name='fabrication_batches')
    op.drop_index('ix_fabrication_batches_experiment_id', table_name='fabrication_batches')
    op.drop_table('fabrication_batches')
    op.drop_index('ix_baseline_versions_baseline_id', table_name='baseline_versions')
    op.drop_table('baseline_versions')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_experiments_campaign_id_id', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_campaigns_status_id', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('baselines')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    op.drop_index('ix_audit_events_actor_user_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_index('ix_device_layout_versions_code', table_name='device_layout_versions')
    op.drop_table('device_layout_versions')
    # ### end Alembic commands ###
